### ISSUE TITLE
Add SPDX `license` to `package.json` and license file

### ISSUE THREAD

**Issue by brettz9** [mocha-community/json-file-reporter#17]
Hi,

Please add both:

1. a valid license to the repo
2. a proper SPDX identifier, e.g., "MIT", to your `package.json`. There are automated license-checkers and license badge-builders which use this info for auditing/reporting on used licenses.

Thanks!

**Comment by brettz9** [comment]
@munierujp : Could I get a reply on this? Thanks...

**Comment by brettz9** [comment]
If someone from the project could indicate the desired license, I can prepare a PR.  Is it just MIT as with Mocha itself?

**Comment by munierujp** [comment]
@brettz9 Unfortunately, I have no knowledge of software licenses, so I was wondering which one to choose. But, the MIT license seems a good choice. Could you do that?
